/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "tertiary-container": "#607087",
          "outline-variant": "#e2e8f0",
          "primary-fixed-dim": "#b4c5ff",
          "primary-container": "#0062ff",
          "error": "#ba1a1a",
          "surface-dim": "#f1f5f9",
          "background": "#ffffff",
          "surface-container-lowest": "#ffffff",
          "on-surface": "#0f172a",
          "on-tertiary": "#ffffff",
          "surface-bright": "#ffffff",
          "on-secondary-fixed": "#001f27",
          "surface-container": "#f8fafc",
          "on-secondary": "#ffffff",
          "surface-container-high": "#f1f5f9",
          "surface": "#ffffff",
          "surface-variant": "#f1f5f9",
          "tertiary-fixed-dim": "#b7c8e1",
          "tertiary-fixed": "#d3e4fe",
          "on-tertiary-container": "#eef3ff",
          "on-primary-container": "#f3f3ff",
          "secondary-fixed": "#b3ebff",
          "primary-fixed": "#dbe1ff",
          "inverse-on-surface": "#ecf1ff",
          "on-surface-variant": "#475569",
          "inverse-surface": "#263143",
          "surface-tint": "#0053da",
          "surface-container-highest": "#e2e8f0",
          "inverse-primary": "#b4c5ff",
          "on-background": "#0f172a",
          "on-primary-fixed-variant": "#003ea8",
          "on-primary-fixed": "#00174b",
          "outline": "#94a3b8",
          "secondary-fixed-dim": "#4cd6fb",
          "primary": "#0f172a",
          "on-secondary-fixed-variant": "#004e5f",
          "on-error-container": "#93000a",
          "tertiary": "#48586d",
          "surface-container-low": "#f8fafc",
          "on-tertiary-fixed-variant": "#38485d",
          "error-container": "#ffdad6",
          "secondary": "#334155",
          "secondary-container": "#50d9fe",
          "on-tertiary-fixed": "#0b1c30",
          "on-secondary-container": "#005c70",
          "on-primary": "#ffffff",
          "on-error": "#ffffff",
          "accent": "#0053da"
      },
      "borderRadius": {
          "DEFAULT": "4px",
          "lg": "8px",
          "xl": "12px",
          "full": "9999px"
      },
      "spacing": {
          "margin-mobile": "24px",
          "margin-desktop": "80px",
          "base": "8px",
          "md": "24px",
          "gutter": "32px",
          "lg": "48px",
          "xl": "96px",
          "2xl": "128px",
          "xs": "4px",
          "sm": "12px"
      },
      "fontFamily": {
          "label-md": ["DM Sans", "sans-serif"],
          "headline-lg": ["Syne", "sans-serif"],
          "headline-lg-mobile": ["Syne", "sans-serif"],
          "headline-md": ["Syne", "sans-serif"],
          "headline-xl": ["Syne", "sans-serif"],
          "body-lg": ["DM Sans", "sans-serif"],
          "headline-xl-mobile": ["Syne", "sans-serif"],
          "headline-sm": ["Syne", "sans-serif"],
          "body-sm": ["DM Sans", "sans-serif"],
          "body-md": ["DM Sans", "sans-serif"]
      },
      "fontSize": {
          "label-md": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-lg": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
          "headline-xl": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-xl-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
          "body-sm": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
